### PR TITLE
Pin leftover pipeline-java containers to 4.4.0

### PR DESCRIPTION
**Pull request by alourie**
# Description

Pin the leftover `pipeline-java` containers missed in #38  to version 4.4.0.

### Code
- [x] I have performed a self review of my own code (including checking issues raised when creating the PR).
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
~- [ ] I have handled all new warnings generated by the compiler or IDE.~
- [x] I have rebased onto the target branch (usually main).
      
### Documentation
~- [ ] I have updated the changelog.~
~- [ ] I have updated any documentation required for these changes.~

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [OPS-216 Pin java pipelines to 4.4.0 for all pipeline-java flows](https://app.clickup.com/t/6929263/OPS-216)

**Review by zarakay — COMMENTED** [review]
This breaks the pom dependency caching that used to be done in the ewb/ednar super pom repos. Do we care? Are we going to look at restoring that?

**Comment by alourie** [comment]
> This breaks the pom dependency caching that used to be done in the ewb/ednar super pom repos. Do we care? Are we going to look at restoring that?

Yea, so I'm currently still looking at why are we even building containers in those repos - it makes no sense whatsoever...but at the very least this PR will fix the failing jobs in the meanwhile.

**Comment by charlta** [comment]
> > This breaks the pom dependency caching that used to be done in the ewb/ednar super pom repos. Do we care? Are we going to look at restoring that?
> 
> Yea, so I'm currently still looking at why are we even building containers in those repos - it makes no sense whatsoever...but at the very least this PR will fix the failing jobs in the meanwhile.

Containers were build in the super pom in an attempt to cache used dependencies for those repos when the super pom changes

**Comment by alourie** [comment]
> > > This breaks the pom dependency caching that used to be done in the ewb/ednar super pom repos. Do we care? Are we going to look at restoring that?
> > 
> > 
> > Yea, so I'm currently still looking at why are we even building containers in those repos - it makes no sense whatsoever...but at the very least this PR will fix the failing jobs in the meanwhile.
> 
> Containers were build in the super pom in an attempt to cache used dependencies for those repos when the super pom changes

Well, we have definitely made a duplicated effort with trying to cache dependencies with containers. I'll probably remove the container creation in the superpom repos and see how we solve caching with github action step properly.

If there's a dependency in Ednar that is not handled in our regular containers, I'll update that too.

**Comment by charlta** [comment]
> Well, we have definitely made a duplicated effort with trying to cache dependencies with containers. I'll probably remove the container creation in the superpom repos and see how we solve caching with github action step properly.
> 
> If there's a dependency in Ednar that is not handled in our regular containers, I'll update that too.

From what I was told (I have not confirmed), regular git actions throw away their caches after a prescribed amount of time, which is often sorter than the cadence of our builds, making it close to useless for most repos.

The intent of the image building was to have the dependencies of the super pom stored in a local maven cache inside the image, and then use the github caching on top of that to build out the missing things (if it is still being used at all). The problem with the super pom dependencies is we don't have everything moving long on the latest super pom, so the dependencies it caches are often the incorrect versions for you repo anyway.

A bigger issue seems to be that we will have an image potentially built from the wrong super pom if we have two competing, making it have even more misses. Remembering that this is not just for the dependencies directly pulled in by the super pom, but all transitive ones as well.

I don't care how you solve it, but making it so that we just use a github cache is unlikely to save time for a lot of repos due to the expiring nature. Please keep this in mind when choosing what you proceed with.

**Comment by alourie** [comment]
I've created a new ticket to consider options at https://app.clickup.com/t/6929263/OPS-217

I've looked into how we hit our github cache - it's valid for 7 days and will be deleted over that time period. For the repositories that building rarely, we might just let them be, and recreate their cache on the spot. For the repositories that build a bit more frequently, we might add an action that spins on a schedule for a simple build, to keep that cache active and hence save the time for builds.

In any case, whatever the implementation is going to be, this PR is still valid, and we'll deal with those other issues separately.

**Review by kgreav — APPROVED** [review]

**Pull request merged**
